### ISSUE TITLE
Rename built-in rules to be all lowercase

### ISSUE THREAD

**Issue by tomtau** [pest-parser/pest3#9]
to make it consistent, since they are not separated by the `pest::` module

**Comment by chriskrycho** [comment]
I’d be happy to do this. To make sure I don’t waste either of our time, though: these, and the others like them in this file?

https://github.com/pest-parser/pest3/blob/08e99257b9d2e9befefe48d655fca9ca9e979f0e/pest/src/typed/template/mod.rs#L1022-L1059

Or something somewhere else?

**Comment by TheVeryDarkness** [comment]
@chriskrycho Yes, and you could also update the generates imports here:

https://github.com/pest-parser/pest3/blob/08e99257b9d2e9befefe48d655fca9ca9e979f0e/generator/src/typed/output.rs#L146-L170

Maybe you could also remove these two lines:

https://github.com/pest-parser/pest3/blob/08e99257b9d2e9befefe48d655fca9ca9e979f0e/generator/src/typed/module.rs#L309-L310

**Comment by chriskrycho** [comment]
@tomtau feel free! I will carve out some time later this week or early next to knock it out. Have been enjoying Pest v2 for working on a small programming language… and also feeling *very* keenly the value that the new stuff in v3 would add!

**Comment by chriskrycho** [comment]
Thank you for not waiting for me. The rest of the year was… not conducive to this contribution. Sorry about that!
